baseURL = "https://www.artsoftheinsane.com/cv"
languageCode = "en-us"
defaultContentLanguage = "en"
theme = "almeida-cv"
title = "CV"
publishDir = "docs"

[params]
colorDark = "#666"
colorLight = "#fff"
colorPageBackground = "#ddd"
colorPrimary = "#e3bfb8"
colorPrimaryText = "#fff"
colorRightColumnBackground = "#f5f5f5"
colorSecondary = "#aaa"
pages = 1
